branches:
  only:
  - master
install:
- curl -o /tmp/pandoc-1.13.1.zip https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.13.1.zip
- unzip -j /tmp/pandoc-1.13.1.zip pandoc-1.13.1/linux/debian/x86_64/pandoc -d ${HOME}/pandoc
- chmod +x ${HOME}/pandoc/pandoc
- export PATH=$PATH:${HOME}/pandoc
- pip install --user ghp-import
- pip install --user -r requirements.txt
script:
- make preview
# Don't publish pull requests
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make publish-travis > /dev/null 2>&1 || true'
- make check
env:
  global:
    secure: roXogK5GYjvHZwrFJlyNdeYbdH1f3piXxM21p8nqOSK5SlT61qw82NQ7/o6KmLQy03aU5NT1vXPMAUHh/VjlChUhQiOs++VhUylTEmbRZFbvprsJwW6Hte8RcYXou8cdmdzVikvy8QG9vtJiiIjvULNjbn1iejiVWF/ZVvjpFawedMMGWzPgPHigcjyk9pcAwCv+gI/QMttFoq8I9R7yj7BBW4ogvChrgQkSbEGRwkyUGPfguvaRqEIf001T8gD/L4x0wM9lLjmMSLxOLKNZSnEF5JnPYkLo8gDptEaHs37s5IZLmUyrlRXGyMWevNrvIdHGgUNNqrXiK732wwjEzopZqHzCteZWssqQbFzjVFIRK/RNiC/1Sf/QI3EG2ufXgBhw310CSKZTdiF4HCzcRiPw+PJqrYKmok236kwWL+Mqp47/lVBfHke3XlXsTUDvCTv7XEJD7HYqDf1zitOoaFHQyeXR44Bh/KCrwlPXJX937O6Vogg+A3z+pS+mgAlf5/daucUlQDLtMHBNmw6QMFk+ZjePjPqDvvKGaeOXfd7Iil1AouXFcrvun6MTESrrmWyXyiUNUpqYNQXzclk5c00mwPxxUdent6ZkMHKiLUPJ1BxGpHopcMMv5eAVUEg/UQLuG78AeDFjx1DOuxPul/E8bnphy/hUEumxTBE+KBA=
notifications:
  slack: lhcb:KdB2DzrWqbbhWJ4XejrY6YSX
  email: false
